"""Unit tests for the envelopes module."""
from __future__ import annotations

import json

import pytest

import envelopes


VALID_SHA = "a" * 40


def _request(**overrides):
    base = dict(
        command="echo",
        args={"message": "hi"},
        branch="main",
        commit_sha=VALID_SHA,
        subagent_id="harness-batch-job",
        submitted_at="2026-05-17T00:00:00Z",
    )
    base.update(overrides)
    return base


# ---------------------------------------------------------------------------
# build_request
# ---------------------------------------------------------------------------
class TestBuildRequest:
    def test_sets_required_markers(self):
        env = envelopes.build_request(**_request())
        assert env["protocol_version"] == 1
        assert env["kind"] == "batch-job-request"

    def test_copies_args(self):
        original = {"message": "hi"}
        env = envelopes.build_request(**_request(args=original))
        # Returned dict is decoupled from caller's dict.
        original["message"] = "mutated"
        assert env["args"] == {"message": "hi"}

    def test_handles_none_args(self):
        env = envelopes.build_request(**_request(args=None))
        assert env["args"] == {}

    def test_no_run_status_initially(self):
        env = envelopes.build_request(**_request())
        assert "run_status" not in env

    def test_rejects_empty_command(self):
        with pytest.raises(ValueError, match="command"):
            envelopes.build_request(**_request(command=""))

    def test_rejects_empty_branch(self):
        with pytest.raises(ValueError, match="branch"):
            envelopes.build_request(**_request(branch=""))

    def test_rejects_short_sha(self):
        with pytest.raises(ValueError, match="commit_sha"):
            envelopes.build_request(**_request(commit_sha="abc123"))

    def test_rejects_non_string_sha(self):
        with pytest.raises(ValueError, match="commit_sha"):
            envelopes.build_request(**_request(commit_sha=None))

    def test_rejects_empty_subagent_id(self):
        with pytest.raises(ValueError, match="subagent_id"):
            envelopes.build_request(**_request(subagent_id=""))

    def test_rejects_empty_submitted_at(self):
        with pytest.raises(ValueError, match="submitted_at"):
            envelopes.build_request(**_request(submitted_at=""))


# ---------------------------------------------------------------------------
# serialize
# ---------------------------------------------------------------------------
class TestSerialize:
    def test_round_trips_through_json(self):
        env = envelopes.build_request(**_request())
        text = envelopes.serialize(env)
        parsed = json.loads(text)
        assert parsed == env

    def test_uses_indent_two(self):
        env = envelopes.build_request(**_request())
        text = envelopes.serialize(env)
        # The first nested key should be indented with exactly 2 spaces.
        assert '\n  "protocol_version"' in text

    def test_preserves_key_order(self):
        env = envelopes.build_request(**_request())
        text = envelopes.serialize(env)
        # protocol_version comes before kind, which comes before command.
        i_pv = text.index('"protocol_version"')
        i_kind = text.index('"kind"')
        i_cmd = text.index('"command"')
        assert i_pv < i_kind < i_cmd


# ---------------------------------------------------------------------------
# parse — lenient prefix
# ---------------------------------------------------------------------------
class TestParse:
    def test_parses_valid_envelope(self):
        env = envelopes.build_request(**_request())
        text = envelopes.serialize(env)
        assert envelopes.parse(text) == env

    def test_tolerates_trailing_prose(self):
        env = envelopes.build_request(**_request())
        text = envelopes.serialize(env) + "\n\n---\n_Generated by Claude Code_\n"
        assert envelopes.parse(text) == env

    def test_tolerates_leading_whitespace(self):
        env = envelopes.build_request(**_request())
        text = "\n\n   " + envelopes.serialize(env)
        assert envelopes.parse(text) == env

    def test_rejects_none(self):
        assert envelopes.parse(None) is None

    def test_rejects_empty_string(self):
        assert envelopes.parse("") is None
        assert envelopes.parse("   \n  ") is None

    def test_rejects_non_string(self):
        assert envelopes.parse(42) is None  # type: ignore[arg-type]
        assert envelopes.parse({}) is None  # type: ignore[arg-type]

    def test_rejects_non_object_json(self):
        assert envelopes.parse('[1, 2, 3]') is None
        assert envelopes.parse('"a string"') is None
        assert envelopes.parse("42") is None

    def test_rejects_object_without_markers(self):
        assert envelopes.parse('{"foo": "bar"}') is None
        assert envelopes.parse('{"protocol_version": 1}') is None
        assert envelopes.parse('{"kind": "x"}') is None

    def test_rejects_malformed_json(self):
        assert envelopes.parse("{not json") is None
        # Prose-first bodies don't parse because raw_decode hits prose first.
        assert envelopes.parse("hello there {}") is None

    def test_accepts_minimal_object_with_markers(self):
        # Even if other required fields are missing, parse only enforces
        # the two protocol markers. Schema-validation is handler.py's job.
        parsed = envelopes.parse(
            '{"protocol_version": 1, "kind": "batch-job-request"}'
        )
        assert parsed == {"protocol_version": 1, "kind": "batch-job-request"}


# ---------------------------------------------------------------------------
# run_status / is_* accessors
# ---------------------------------------------------------------------------
class TestRunStatusAccessors:
    def test_run_status_none(self):
        env = envelopes.build_request(**_request())
        assert envelopes.run_status(env) is None
        assert envelopes.is_terminal(env) is False
        assert envelopes.is_completed(env) is False
        assert envelopes.is_running(env) is False

    def test_run_status_running(self):
        env = dict(envelopes.build_request(**_request()), run_status="running")
        assert envelopes.run_status(env) == "running"
        assert envelopes.is_running(env) is True
        assert envelopes.is_terminal(env) is False

    @pytest.mark.parametrize(
        "status,is_completed,is_error,is_pe",
        [
            ("completed", True, False, False),
            ("error", False, True, False),
            ("parse_error", False, False, True),
        ],
    )
    def test_terminal_statuses(self, status, is_completed, is_error, is_pe):
        env = dict(envelopes.build_request(**_request()), run_status=status)
        assert envelopes.is_terminal(env) is True
        assert envelopes.is_completed(env) is is_completed
        assert envelopes.is_error(env) is is_error
        assert envelopes.is_parse_error(env) is is_pe

    def test_status_accessors_on_non_dict(self):
        assert envelopes.run_status(None) is None  # type: ignore[arg-type]
        assert envelopes.is_terminal({}) is False
        assert envelopes.is_terminal({"run_status": "weird"}) is False
        assert envelopes.is_terminal({"run_status": None}) is False


# ---------------------------------------------------------------------------
# Module surface
# ---------------------------------------------------------------------------
class TestExports:
    def test_known_constants(self):
        assert envelopes.PROTOCOL_VERSION == 1
        assert envelopes.KIND_REQUEST == "batch-job-request"
        assert envelopes.KIND_ACK == "agent-ack"
        assert set(envelopes.TERMINAL_STATUSES) == {
            "completed",
            "error",
            "parse_error",
        }

    def test_all_lists_public_names(self):
        for name in envelopes.__all__:
            assert hasattr(envelopes, name), f"__all__ references missing {name!r}"
